version: "2"

services:

  web-ui:
    image: petstore-kafka/web-ui:latest
    restart: always
    ports:
      - "4000:5000"
    environment:
      PETS_HOST: "http://pets"
      ADOPTIONS_HOST: "http://adoptions"
      WEBSOCKET_HOST: "http://websocket"

  pets:
    image: petstore-kafka/pets:latest
    restart: always
    environment:
      KAFKA_HOST: "http://kafka"

  adoptions:
    image: petstore-kafka/adoptions:latest
    restart: always
    environment:
      KAFKA_HOST: "http://kafka"

  websocket:
    image: petstore-kafka/websocket:latest
    restart: always
    environment:
      KAFKA_HOST: "http://kafka"

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    hostname: kafka.local
    depends_on:
      - zookeeper
  cmak:
      image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5:latest
      restart: always
      ports:
        - "9000:9000"
      environment:
        ZK_HOSTS: "zookeeper:2181"
      depends_on:
        - zookeeper
        - kafka
    

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
